- name: ec2 instance creation
  hosts: local
  connection: local
  become: yes
  vars:
   ami_id: ami-09c813fb71547fc4f
   sg_id: sg-02704cfa1a0558868
   zone_id: Z09770583FTSAJKH9PBLF
   domain_name: "daws-practice.fun"   
  #  instances:
  #  - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     instance_type: t3.micro
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     tags:
      name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2 instance output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"  

  - name: create route 53 record
    amazon.aws.route53:
     state: present
     zone: "{{ domain_name }}"
     record: "{{ item.item }}.{{ domain_name }}"
     type: A
     ttl: 1
     value: "{{ item.instances[0].private_ip_address }}"
     overwrite: true
    loop: "{{ ec2_output.results }}"    

  - name: create route 53 record
    amazon.aws.route53:
     state: present
     zone: "{{ domain_name }}"
     record: "{{ domain_name }}"
     type: A
     ttl: 1
     value: "{{ item.instances[0].public_ip_address }}"
     overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"