- name: deploy cart service
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -

  - name: install nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: adduser roboshop
    ansible.builtin.user:
     name: roboshop
     comment: "roboshop system user"
     shell: /sbin/nologin
     home: /app      

  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: delete zip file
    ansible.builtin.file:
     path: /tmp/cart.zip
     state: absent

  - name: download cart files
    ansible.builtin.unarchive:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: install dependencies
    community.general.npm:
     path: /app

  - name: copy cart service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: start cart service
    ansible.builtin.systemd_service:
     daemon-reload: true
     name: cart
     state: restarted
     enabled: true      