- name: isntalling mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copying mongo repo
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:
     name: mongodb-org
     state: present

  - name: start and enable mongodb service
    ansible.builtin.systemd_service:
     name: mongodb
     state: restarted
     enabled: true    