- name: install mysql database
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql db
    ansible.builtin.dnf:
     name: mysql-server
     state: present

  - name: mysql service
    ansible.builtin.systemd_service:
     name: mysqld
     state: restarted
     enabled: true

  - name: set root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1      