- name: install rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: add rabbitmq to repo
    ansible.builtin.copy:
     src: rabbitmq.repo
     dest: /etc/yum.repos.d/rabbitmq.repo 

  - name: insall rabbitmq
    ansible.builtin.package:
     name: rabbitmq-server
     state: present

  - name: start rabbitmq service
    ansible.builtin.systemd_service:
     name: rabbitmq-server
     start: restarted
     enabled: true

  - name: create user and set password
    community.rabbitmq.rabbitmq_user:
     user: roboshop
     password: roboshop123
     permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
     state: present