- name: install rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: insall rabbitmq
    ansible.builtin,dnf:
     name: rabbitmq-server
     state: present

  - name: start rabbitmq service
    ansible.builtin.systemd_service:
     name: rabbitmq
     start: started
     enabled: true

  - name: create user and set password
    community.rabbitmq.rabbitmq_user:
     user: roboshop
     password: roboshop123
     permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
     state: present